version: "3.9"

secrets:
  cloudflared_token:
    external: true

services:
  cloudflared:
    image: cloudflare/cloudflared:latest
    command: tunnel run --token-file /run/secrets/cloudflared_token
    secrets:
      - cloudflared_token

  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - cloudflared